name: Student App Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - ready_for_review
    branches:
      - master

jobs:
  check_pull_request_type:
    name: Check labels on PR
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: category:new-feature,category:bug-fix,category:changes,dev:new-feature,dev:bug-fix,dev:refactoring,dev:changes
          none_of: WIP,Old,wontfix
          repo_token: ${{ secrets.GITHUB_TOKEN }}